import {VERBS,HOTSPOTS,TALK,newState,findPath,pointInPolygon} from './data.js';
import {AudioEngine} from './audio.js';
const $=id=>document.getElementById(id), canvas=$('canvas'),ctx=canvas.getContext('2d'),audio=new AudioEngine();
const images={},frames={},W=960,H=600;
let state=newState(),scene='title',verb='MIRAR',selected=null,hover=null,busy=false,epoch=0,last=performance.now(),clock=0;
let player={x:229,y:551,dir:0,visible:false,pose:null},path=[],moveResolve=null,speed=135,stepClock=0;
let carX=-300,carVisible=false,pedroPose=3,elevatorOpen=0,breath=0,primAlert=0;
let speechResolve=null,typing=null,fullLine='',typed=0,speechTimer=null,toastTimer=null;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function assertEpoch(e){if(e!==epoch)throw new Error('cancelled');}
function setScene(s){scene=s;$('hotspots').hidden=s!=='lobby';$('location').textContent=s==='lobby'?'COLEGIO MAYOR DEUSTO · RECEPCIÓN':'BILBAO · OCTUBRE DE 1994';}
function toast(t){$('toast').textContent=t;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,2600);}
function showTransition(t){$('transition-text').innerHTML=t;$('transition').hidden=false;}
function hideTransition(){$('transition').hidden=true;}
function setSentence(){if(scene!=='lobby')return;const obj=hover?HOTSPOTS.find(h=>h.id===hover)?.name:'';$('sentence').textContent=selected?`${verb} ${itemName(selected)}${obj?' CON '+obj.toUpperCase():''}`:`${verb}${obj?' '+obj.toUpperCase():''}`;}
function itemName(id){return {bag:'maleta marrón',key:'llave 310',marca:'Marca',correo:'El Correo',mundo:'El Mundo',abc:'ABC'}[id]||id;}
function refreshInventory(){const items=['bag',...(state.hasKey310?['key']:[]),...state.tookPapers];$('count').textContent=String(items.length).padStart(2,'0');$('items').replaceChildren();for(const id of items){const b=document.createElement('button');b.dataset.item=id;b.className=selected===id?'selected':'';b.setAttribute('aria-label',itemName(id));const icon=document.createElement('span');icon.className='symbol';icon.textContent=id==='key'?'⚿':id==='bag'?'▣':'▤';if(images.walk&&images.actions){const ic=document.createElement('canvas');ic.width=48;ic.height=40;ic.setAttribute('aria-hidden','true');const ig=ic.getContext('2d');ig.imageSmoothingEnabled=false;if(id==='bag'){ig.drawImage(frames.walk[0],frames.walk[0].width*.59,frames.walk[0].height*.56,frames.walk[0].width*.41,frames.walk[0].height*.36,13,2,24,36);}else if(id==='key'){ig.drawImage(frames.actions[6],0,45,28,65,16,0,17,40);}else{const h=HOTSPOTS.find(h=>h.id===id),[x,y,w,hh]=h.rect;ig.drawImage(images.reception,x/960*1448,y/600*1086,w/960*1448,hh/600*1086,3,8,42,26);}b.append(ic);}else b.append(icon);b.append(document.createTextNode(itemName(id)));b.onclick=()=>inventoryClick(id);$('items').append(b);}}
function selectVerb(v){if(busy||scene!=='lobby')return;verb=v;selected=null;for(const b of $('verbs').children)b.classList.toggle('active',b.textContent===v);refreshInventory();setSentence();}
for(const v of VERBS){const b=document.createElement('button');b.textContent=v;b.className=v===verb?'active':'';b.onclick=()=>selectVerb(v);$('verbs').append(b);}
function setHotspots(){for(const h of HOTSPOTS){const b=document.createElement('button');b.setAttribute('aria-label',h.name);b.dataset.hotspot=h.id;b.style.zIndex=h.id==='reception'?'1':'2';const [x,y,w,hg]=h.rect;Object.assign(b.style,{left:x/W*100+'%',top:y/H*100+'%',width:w/W*100+'%',height:hg/H*100+'%'});const span=document.createElement('span');span.textContent=h.name;b.append(span);b.onmouseenter=b.onfocus=()=>{hover=h.id;setSentence();};b.onmouseleave=b.onblur=()=>{hover=null;setSentence();};b.onclick=e=>{e.stopPropagation();interact(h);};b.ondblclick=e=>{e.stopPropagation();speed=310;};$('hotspots').append(b);}}
function cancelSpeech(){clearInterval(typing);clearTimeout(speechTimer);typing=null;$('speech').hidden=true;const r=speechResolve;speechResolve=null;if(r)r();}
function nextSpeech(){if(!speechResolve)return;if(typed<fullLine.length){typed=fullLine.length;$('line').textContent=fullLine;clearInterval(typing);typing=null;return;}cancelSpeech();}
function say(who,text,auto=false){cancelSpeech();$('choices').hidden=true;$('speaker').textContent=who.toUpperCase();fullLine=text;typed=0;$('line').textContent='';$('speech').hidden=false;pedroPose=who==='Pedro'?1:3;if(who==='Julito'&&scene==='lobby')player.pose=0;return new Promise(resolve=>{speechResolve=()=>{player.pose=null;pedroPose=3;resolve();};typing=setInterval(()=>{typed=Math.min(fullLine.length,typed+2);$('line').textContent=fullLine.slice(0,typed);if(typed===fullLine.length){clearInterval(typing);typing=null;}},24);if(auto)speechTimer=setTimeout(cancelSpeech,Math.max(2800,text.length*52));});}
$('next').onclick=e=>{e.stopPropagation();nextSpeech();};$('speech').onclick=nextSpeech;
async function lines(list,auto=false,e=epoch){for(const [who,text] of list){assertEpoch(e);await say(who,text,auto);assertEpoch(e);}}
async function speak(text,who='Julito'){await say(who,text);}
function walk(to,fast=false,direct=false){if(moveResolve){moveResolve(false);moveResolve=null;}path=direct?[to]:findPath([player.x,player.y],to)||[];speed=fast?310:135;if(!path.length)return Promise.resolve(false);player.pose=null;return new Promise(r=>moveResolve=r);}
function renderFrame(sprite,x,y,height,flip=false){if(!sprite)return;const width=sprite.width/sprite.height*height;ctx.save();ctx.translate(Math.round(x),Math.round(y));if(flip)ctx.scale(-1,1);ctx.drawImage(sprite,Math.round(-width/2),-Math.round(height),Math.round(width),Math.round(height));ctx.restore();}
function renderPlayer(){if(!player.visible)return;const scale=scene==='exterior'?.67:Math.max(.64,Math.min(1.12,(player.y-150)/360));let f;if(player.pose!==null)f=frames.actions[player.pose];else {const index=path.length?1+Math.floor(clock*7)%3:0;f=frames.walk[(player.dir===1?4:player.dir>=2?8:0)+index];}renderFrame(f,player.x,player.y,142*scale,player.dir===3);}
function draw(t){const dt=Math.min((t-last)/1000,1);last=t;clock+=dt;breath=Math.sin(clock*1.8);if(path.length){const dest=path[0],dx=dest[0]-player.x,dy=dest[1]-player.y,d=Math.hypot(dx,dy);player.dir=Math.abs(dx)>Math.abs(dy)*.7?(dx>=0?2:3):(dy<0?1:0);if(d<speed*dt){player.x=dest[0];player.y=dest[1];path.shift();if(!path.length&&moveResolve){const r=moveResolve;moveResolve=null;r(true);}}else{player.x+=dx/d*speed*dt;player.y+=dy/d*speed*dt;}stepClock+=dt;if(stepClock>.33){stepClock=0;audio.effect('step');}}
ctx.imageSmoothingEnabled=false;ctx.clearRect(0,0,W,H);
if(images.exterior){ctx.drawImage(scene==='lobby'||scene==='end'?images.reception:images.exterior,0,0,W,H);if(scene==='title'||scene==='exterior'){ctx.fillStyle=`rgba(255,221,125,${.035+.025*Math.sin(clock*2)})`;ctx.fillRect(502,390,19,13);if(carVisible)ctx.drawImage(images.passat,Math.round(carX),442,300,150);if(scene==='exterior')renderPlayer();}
if(scene==='lobby'||scene==='end'){
// Pedro is composited behind the existing desk and glazing, preserving depth.
ctx.save();ctx.beginPath();ctx.rect(72,183,126,115);ctx.clip();renderFrame(frames.pedro[pedroPose],148,340,147);ctx.restore();
if(images.prim){const cellW=images.prim.width/2;ctx.drawImage(images.prim,primAlert>clock?cellW:0,40,cellW,180,205,355,128,90+breath*.4);}
if(elevatorOpen>0){const a=HOTSPOTS.find(h=>h.id==='elevator').rect;ctx.save();ctx.beginPath();ctx.rect(594,205,30,67);ctx.clip();ctx.fillStyle='#161818';ctx.fillRect(606-elevatorOpen*13,205,elevatorOpen*26,67);ctx.restore();ctx.fillStyle='#f3c474';ctx.fillRect(580,229,3,4);}
renderPlayer();}
}requestAnimationFrame(draw);}
function spriteFrames(img){const xs=[60,350,625,900,1215],ys=[0,313,620,926,1254],out=[];for(let row=0;row<4;row++)for(let col=0;col<4;col++){const sw=xs[col+1]-xs[col],sh=ys[row+1]-ys[row],c=document.createElement('canvas');c.width=sw;c.height=sh;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(img,xs[col],ys[row],sw,sh,0,0,sw,sh);const data=g.getImageData(0,0,sw,sh),d=data.data,seen=new Uint8Array(sw*sh),q=[];
function visit(i){if(i<0||i>=sw*sh||seen[i])return;seen[i]=1;const k=i*4,r=d[k],gg=d[k+1],b=d[k+2];if(r>170&&gg>165&&b>145&&Math.max(r,gg,b)-Math.min(r,gg,b)<65){d[k+3]=0;q.push(i);}}
for(let x=0;x<sw;x++){visit(x);visit((sh-1)*sw+x);}for(let y=0;y<sh;y++){visit(y*sw);visit(y*sw+sw-1);}for(let n=0;n<q.length;n++){const i=q[n],x=i%sw;if(x>0)visit(i-1);if(x<sw-1)visit(i+1);visit(i-sw);visit(i+sw);}g.putImageData(data,0,0);let l=sw,r=0,top=sh,bottom=0;for(let y=0;y<sh;y++)for(let x=0;x<sw;x++)if(d[(y*sw+x)*4+3]){l=Math.min(l,x);r=Math.max(r,x);top=Math.min(top,y);bottom=Math.max(bottom,y);}const trimmed=document.createElement('canvas');trimmed.width=r-l+1;trimmed.height=bottom-top+1;trimmed.getContext('2d').drawImage(c,l,top,trimmed.width,trimmed.height,0,0,trimmed.width,trimmed.height);out.push(trimmed);}return out;}
async function intro(){const e=++epoch;busy=true;state=newState();refreshInventory();$('title').hidden=true;$('skip').hidden=false;$('sentence').textContent='Bilbao. Octubre de 1994.';audio.setTheme('exterior');setScene('exterior');showTransition('BILBAO<small>Octubre de 1994</small>');try{await sleep(1700);assertEpoch(e);hideTransition();carVisible=true;carX=-330;audio.effect('engine');for(let i=0;i<=90;i++){assertEpoch(e);carX=-330+i*8;await sleep(25);}audio.effect('door');player.visible=true;player.x=504;player.y=499;player.dir=0;await sleep(400);assertEpoch(e);audio.effect('case');await lines([['Desde el coche','¡Escribe cuando llegues!'],['Julito','Pero si ya he llegado.']],true,e);audio.effect('engine');for(let i=0;i<75;i++){assertEpoch(e);carX+=10;await sleep(22);}carVisible=false;await lines([['Julito','Bueno… pues aquí empieza todo.'],['Julito','Mi madre ha metido ropa para cuatro años. La carrera dura cinco.']],true,e);player.pose=11;audio.effect('case');await sleep(1400);assertEpoch(e);player.pose=null;await walk([513,427],false,true);assertEpoch(e);audio.effect('door');showTransition('COLEGIO MAYOR DEUSTO');await sleep(1300);assertEpoch(e);enterLobby();busy=true;await walk([300,498]);busy=false;}catch(err){if(err.message!=='cancelled')throw err;}}
function enterLobby(){epoch++;cancelSpeech();if(moveResolve)moveResolve(false);moveResolve=null;path=[];carVisible=false;player={x:229,y:551,dir:1,visible:true,pose:null};$('title').hidden=true;$('skip').hidden=true;hideTransition();setScene('lobby');state.introCompleted=true;busy=false;audio.setTheme('lobby');$('hint').textContent='Elige un verbo y un objeto. Doble clic para caminar más deprisa.';setSentence();refreshInventory();}
$('skip').onclick=()=>enterLobby();
async function conversation(){if(!state.talkedToPedro){await lines(TALK.welcome);state.talkedToPedro=true;}else if(state.hasKey310)await lines(TALK.after);showChoices();}
function showChoices(){const options=[...(!state.hasKey310?[['key','Vengo a por la llave de mi habitación.']]:[]),['place','¿Dónde estoy exactamente?'],['rules','¿Hay alguna norma que debería conocer?'],['weather','¿Siempre hace este tiempo en Bilbao?'],['suitcase','¿Pasa algo con mi maleta?'],['prim','¿Y este perro?'],['bye','Eso es todo. Gracias, Pedro.']];$('choices').replaceChildren();for(const [id,label] of options){const b=document.createElement('button');b.textContent=(state.readTopics.includes(id)?'· ':'')+label;b.onclick=async()=>{$('choices').hidden=true;if(id==='bye'){await speak('Los ascensores están al fondo. La aventura ya es cosa tuya.','Pedro');busy=false;return;}if(id==='prim'){await lines([['Pedro','Prim. Pastor alemán. Recepcionista adjunto.'],['Julito','¿Y qué hace?'],['Pedro','Lo mismo que yo, pero cae mejor.'],['Pedro','Siempre está aquí. Si se levanta, será por algo.']]);}else{await lines(TALK[id]);}if(!state.readTopics.includes(id))state.readTopics.push(id);if(id==='key'){pedroPose=6;player.pose=6;audio.effect('key');await sleep(650);state.roomAssigned=true;state.hasKey310=true;player.pose=null;pedroPose=3;refreshInventory();toast('Has conseguido: LLAVE 310');await speak('Los ascensores están al fondo. Y no pierdas la llave: el duplicado también está perdido.','Pedro');}if(id==='suitcase')primAlert=clock+5;showChoices();};$('choices').append(b);}$('choices').hidden=false;}
function showPaper(id){const info={marca:['MARCA','LA FÁBRICA','La cantera del Real Madrid prepara una nueva generación.','El futuro vuelve a vestirse de blanco.'],correo:['EL CORREO','BILBAO ESTRENA CURSO','Maletas, apuntes y paraguas regresan a la ciudad.','La universidad vuelve a llenar las calles.'],mundo:['EL MUNDO','UN PAÍS EN MARCHA','La actualidad no espera a que termines de hacer la maleta.','Edición de la mañana.'],abc:['ABC','OCTUBRE EN LA UNIVERSIDAD','Comienza otro curso. Se recomienda leer la letra pequeña.','Y todas las demás.']}[id];$('card').innerHTML=`<small>OCTUBRE DE 1994 · PORTADA FICTICIA</small><h2>${info[0]}</h2><h3>${info[1]}</h3><p>${info[2]}</p><hr><p>${info[3]}</p><button>DEJAR DE LEER</button>`;$('card').hidden=false;return new Promise(r=>{$('card').querySelector('button').onclick=()=>{$('card').hidden=true;r();};});}
async function inventoryClick(id){if(busy||scene!=='lobby')return;if(verb==='USAR'||verb==='DAR'){selected=selected===id?null:id;refreshInventory();setSentence();return;}busy=true;if(id==='key')await speak('Habitación 310. Una llave de verdad, con un llavero que podría usarse de pisapapeles.');else if(id==='bag'){if(verb==='ABRIR'){player.pose=10;await speak('Mejor en la habitación. Si abro aquí, tendré que matricular también los calcetines.');}else await speak('Mi maleta marrón. Tiene más kilómetros que yo y se queja bastante menos.');}else{if(id==='marca')await speak('Sigue hablando del Madrid. No ha mejorado.');await showPaper(id);}player.pose=null;busy=false;}
async function interact(h){if(busy||scene!=='lobby')return;busy=true;try{await walk(h.at);if(selected){await useItem(selected,h);selected=null;refreshInventory();setSentence();return;}if(verb==='MIRAR'){if(h.flag)state[h.flag]=true;if(h.id==='board'){await lines([['Julito','KULTURA / CULTURA. KIROLA / DEPORTE. EZTABAIDA / DEBATE. BIZIKIDETZA / CONVIVENCIA.'],['Julito','Cinefórum el jueves. Ajedrez los martes. Se busca portero que no tenga prácticas por la tarde.'],['Julito','Hay un aviso escrito a mano: «No dejar equipaje sin vigilancia». Muy específico.']]);}else if(h.id==='marca'){await showPaper('marca');await speak('Ya están otra vez con la cantera.');}else if(h.id==='prim')await speak('Prim. Pastor alemán. Tiene cara de saber quién vuelve tarde y de no contarlo.');else await speak(h.look||'No parece esconder nada. Eso siempre es sospechoso.');return;}
if(verb==='HABLAR CON'){if(h.id==='pedro'){await conversation();return;}if(h.id==='prim'){primAlert=clock+6;await lines([['Julito','Hola, Prim. Yo soy Julito.'],['Julito','¿Tú también acabas de llegar?'],['Pedro','Lleva más tiempo que tú. Y ya conoce las normas.']]);return;}await speak('No contesta. Primer contacto social: mejorable.');return;}
if(['correo','mundo','abc','marca'].includes(h.id)&&verb==='COGER'){if(!state.tookPapers.includes(h.id)){state.tookPapers.push(h.id);if(h.id==='marca')state.hasMarca=true;audio.effect('paper');player.pose=4;refreshInventory();toast('Has cogido: '+h.name);await showPaper(h.id);await speak(h.id==='marca'?'Ya están otra vez con la cantera.':h.look);player.pose=null;}else await speak('Ya lo tengo. Con una edición me llega.');return;}
if(h.id==='elevator'&&['USAR','ABRIR','EMPUJAR'].includes(verb)){await elevator();return;}
if(h.id==='prim'&&verb==='USAR'){player.pose=8;primAlert=clock+7;await lines([['Julito','Buen chico, Prim.'],['Pedro','Ya has hecho tu primer amigo.'],['Julito','Tiene buen criterio.'],['Pedro','También ha intentado hacerse amigo de tu maleta.']]);player.pose=null;return;}
if(h.id==='sofa'&&verb==='USAR'){player.pose=11;await speak('Cómodo no es exactamente la palabra. Pero la maleta agradece la pausa.');player.pose=null;return;}
if(h.id==='phone'&&verb==='USAR'){audio.effect('bell');await lines([['Pedro','Para llamar a casa, pide línea aquí.'],['Julito','¿Y qué digo?'],['Pedro','Que has llegado. Y que has escrito mentalmente.']]);return;}
if(h.id==='mailbox'&&['ABRIR','COGER'].includes(verb)){await speak('Dime tu habitación y te miro el correo. Desde este lado, mejor no desmontes la conserjería.','Pedro');return;}
if(h.id==='entry'&&['USAR','ABRIR'].includes(verb)){await speak('El Passat ya se ha ido. Primero la llave; luego conquistar Bilbao.');return;}
const defaults={COGER:'Mejor que se quede donde está. Bastante llevo ya.',USAR:'No se me ocurre un uso que mejore mi primera impresión.',ABRIR:'No veo por dónde abrirlo.',CERRAR:'Está suficientemente cerrado para mi gusto.',DAR:'Primero tengo que elegir algo del inventario.',EMPUJAR:'No quiero empezar el curso reorganizando el mobiliario.',TIRAR:'Prefiero no comprobar si está bien sujeto.'};await speak(defaults[verb]||'No parece una buena idea.');
}finally{if($('choices').hidden&&scene!=='end')busy=false;}}
async function useItem(item,h){if(item==='key'&&h.id==='elevator'){await speak('La llave es para la 310. El ascensor, afortunadamente, tiene un botón.');await elevator();return;}if(item==='marca'&&h.id==='pedro'&&verb==='DAR'){await lines([['Pedro','Déjalo en la mesa cuando termines.'],['Julito','¿También le interesa La Fábrica?'],['Pedro','Me interesa que no desaparezcan los periódicos.']]);return;}if(item==='bag'&&h.id==='prim'){primAlert=clock+8;await lines([['Julito','¿Qué has olido, Prim?'],['Pedro','Nada. Será el bocadillo.'],['Julito','No llevo bocadillo.'],['Pedro','Entonces será el recuerdo del bocadillo.']]);return;}if(item==='key'&&h.id==='pedro'&&verb==='DAR'){await speak('Quédatela. Aún no te has instalado y ya quieres hacer la devolución.','Pedro');return;}if(['marca','abc','mundo','correo'].includes(item)&&['marca','abc','mundo','correo'].includes(h.id)){state.tookPapers=state.tookPapers.filter(x=>x!==item);state.hasMarca=state.tookPapers.includes('marca');audio.effect('paper');await speak('Lo dejo en la mesa. Servicio público cumplido.');return;}await speak(h.id==='prim'?'No voy a darle eso a Prim. Seguro que Pedro tiene algo más apropiado.':'No parece que esas dos cosas vayan juntas.');}
async function elevator(){if(!state.hasKey310){await lines(TALK.locked);return;}state.calledElevator=true;audio.effect('elevator');for(let i=0;i<=20;i++){elevatorOpen=i/20;await sleep(35);}audio.effect('bell');await speak('Tercera planta. A ver si la maleta cabe antes que el misterio.');await walk([610,276]);player.visible=false;audio.setTheme('title');showTransition('TERCERA PLANTA');await sleep(1600);setScene('end');$('transition-text').innerHTML='FIN DE LA DEMO<small>Julito volverá en</small>EL MISTERIO DE<br>LA MALETA MARRÓN<small>Prim se queda vigilando.</small><button id="again">VOLVER A JUGAR</button>';$('again').onclick=reset;$('sentence').textContent='Continuará…';busy=false;}
function reset(){epoch++;cancelSpeech();state=newState();selected=null;verb='MIRAR';elevatorOpen=0;path=[];player.visible=false;hideTransition();setScene('title');$('title').hidden=false;$('choices').hidden=true;$('card').hidden=true;$('sentence').textContent='Una maleta. Una llave. Un buen comienzo.';$('hint').textContent='Una aventura para jugar sin prisa.';audio.setTheme('title');busy=false;refreshInventory();for(const b of $('verbs').children)b.classList.toggle('active',b.textContent==='MIRAR');}
$('canvas').onclick=async e=>{if(scene!=='lobby'||busy)return;const r=canvas.getBoundingClientRect(),to=[(e.clientX-r.left)/r.width*W,(e.clientY-r.top)/r.height*H];if(pointInPolygon(to)){selected=null;refreshInventory();setSentence();await walk(to);}};
// Empty parts of the hotspot layer also allow walking.
$('hotspots').onclick=e=>{if(e.target===$('hotspots'))$('canvas').onclick(e);};$('hotspots').ondblclick=e=>{if(scene==='lobby')speed=310;};
$('start').onclick=async()=>{await audio.unlock();intro();};
$('music').onclick=async()=>{await audio.unlock();const on=audio.toggleMusic();$('music').textContent='MÚSICA '+(on?'SÍ':'NO');$('music').setAttribute('aria-pressed',String(on));};
$('sound').onclick=async()=>{await audio.unlock();audio.sound=!audio.sound;$('sound').textContent='SONIDO '+(audio.sound?'SÍ':'NO');$('sound').setAttribute('aria-pressed',String(audio.sound));};
function modal(content){$('modal-body').innerHTML=content;$('modal').showModal();}
$('credits').onclick=()=>modal('<h2>La maleta tiene historia.</h2><p><b>El misterio de la maleta marrón</b><br>Una aventura de Julito en el Colegio Mayor Deusto.</p><p>Idea, personajes y dirección: Mario.<br>Fondos y personajes: material aportado por Mario.<br>Adaptación, programación y música original: Codex.<br>Prim y Passat: ilustraciones creadas para esta demo.</p><p>Bilbao, octubre de 1994. Las portadas y los diálogos son ficción. Una aventura original inspirada en la forma de jugar de los clásicos de los 90.</p>');
$('help').onclick=()=>modal('<h2>Cómo jugar</h2><p>Elige un <b>verbo</b> y pulsa sobre una persona u objeto. Julito se acercará antes de actuar.</p><p><b>Hablar con Pedro</b> es un buen comienzo. Pregunta por tu llave y explora la recepción antes de subir.</p><p>Con <b>USAR</b> o <b>DAR</b>, elige un objeto del inventario y después su destino. <b>USAR Prim</b> permite acariciarlo.</p><p>Pulsa el diálogo para mostrarlo entero y de nuevo para continuar. Doble clic para caminar deprisa. <b>Espacio</b> muestra objetos. <b>Esc</b> salta la introducción.</p>');
$('close-modal').onclick=()=>$('modal').close();$('show-hotspots').onclick=()=>{if(scene==='lobby')$('hotspots').classList.toggle('reveal');};
document.addEventListener('keydown',e=>{if($('modal').open)return;if(e.code==='Space'){e.preventDefault();if(scene==='lobby')$('hotspots').classList.toggle('reveal');}if(e.key==='Escape'){if(scene==='exterior')enterLobby();else if(!$('card').hidden)$('card').querySelector('button').click();else if(!$('choices').hidden){$('choices').hidden=true;busy=false;}else{selected=null;refreshInventory();setSentence();}}if(e.key==='Enter'&&!$('speech').hidden)nextSpeech();});
async function load(){try{await Promise.all(Object.entries({exterior:'exterior.png',reception:'reception.png',walk:'julito-walk.png',actions:'julito-actions.png',pedro:'pedro-actions.png',passat:'passat.png',prim:'prim.png'}).map(([key,file])=>new Promise((resolve,reject)=>{const img=new Image;img.onload=()=>{images[key]=img;resolve();};img.onerror=()=>reject(new Error('No se pudo cargar '+file));img.src='assets/'+file;})));frames.walk=spriteFrames(images.walk);frames.actions=spriteFrames(images.actions);frames.pedro=spriteFrames(images.pedro);setHotspots();refreshInventory();$('hotspots').hidden=true;$('start').disabled=false;$('start').textContent='COMENZAR';requestAnimationFrame(draw);}catch(err){$('start').textContent='REINTENTAR';$('start').disabled=false;$('start').onclick=()=>location.reload();$('sentence').textContent=err.message+'. Pulsa reintentar.';console.error(err);}}
load();
